# Disable non-essential components
alertmanager:
  enabled: false
pushgateway:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
kubeStateMetrics:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
nodeExporter:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
server:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
  persistentVolume:
    enabled: false
  readinessProbeInitialDelay: 0
  # Speed up scraping a bit from the default
  global:
    scrape_interval: 5s
    scrape_timeout: 3s
  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 655
serviceAccounts:
  alertmanager:
    create: false
    name:
    annotations: {}
  nodeExporter:
    create: true
    name:
    annotations: {}
  pushgateway:
    create: true
    name:
    annotations: {}
  server:
    create: true
    name:
    annotations: {}

