# permissions for end users to edit peeringtokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peeringtoken-editor-role
rules:
- apiGroups:
  - consul.hashicorp.com
  resources:
  - peeringtokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - consul.hashicorp.com
  resources:
  - peeringtokens/status
  verbs:
  - get
