{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "consul.fullname" . }}-api-gateway-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: api-gateway-controller
  annotations:
    kubernetes.io/service-account.name: {{ template "consul.fullname" . }}-api-gateway-controller
    {{- if .Values.apiGateway.serviceAccount.annotations }}
    {{ tpl .Values.apiGateway.serviceAccount.annotations . | nindent 4 | trim }}
    {{- end }}
type: kubernetes.io/service-account-token
{{- end }}
